### ISSUE TITLE
Make this repo private

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/Operations#1]
Shouldn't we make this repository private ? This will prevent uncontrolled/unexpected forks by other organizations, and also should prevent players from cheating by investigating a mission's content before playing it.

**Comment by ArwynFr** [comment]
Looking into operations in the editor requires you to clone the whole repository. I don't think a lot of members will try hard to spoil themselves. And if they do, they are clearly out of the spirit of the team and will get some warning and then more drastic actions can be taken.

**Comment by ArwynFr** [comment]
I don't think forking our mission directory is a threat either. Our missions are clearly not so over-the-top quality in the community. Also, if I was to choose a single mission repository to hide, this would be `Tembelan` rather than this one. Or if I was to choose a single repository, that would be `infrastructure`. Also remember that our mission depends on `Opex` and `GZM`, as well as most mods from our modpack to be playable.

**Comment by ImplicitDeny** [comment]
Make sense, closing.
